# Generated by Django 5.2.6 on 2025-09-30 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('location_link', models.URLField(blank=True, max_length=500, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('incident_date', models.DateField()),
                ('report_details', models.TextField()),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('report_type', models.CharField(choices=[('اعتداء', 'اعتداء'), ('ابتزاز', 'ابتزاز'), ('تحرش', 'تحرش'), ('سرقة', 'سرقة'), ('مشادة', 'مشادة')], default='اعتداء', max_length=20)),
                ('status', models.CharField(choices=[('تم استلام البلاغ', 'تم استلام البلاغ'), ('قيد المراجعة', 'قيد المراجعة'), ('قيد المعالجة', 'قيد المعالجة'), ('تم الحل', 'تم الحل'), ('تم الإغلاق', 'تم الإغلاق')], default='تم استلام البلاغ', max_length=20)),
                ('tracking_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(blank=True, choices=[('حرج', 'حرج'), ('عالية', 'عالية'), ('متوسطة', 'متوسطة'), ('منخفضة', 'منخفضة')], max_length=20, null=True)),
                ('is_fake', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CriminalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('other_info', models.TextField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_infos', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_recording', models.FileField(blank=True, null=True, upload_to='attachments/audio/')),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/files/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.report')),
            ],
        ),
    ]
