# Generated by Django 5.2.6 on 2025-09-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_criminal_info_attachment_criminalinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='description',
            new_name='audio_recording',
        ),
        migrations.RenameField(
            model_name='criminalinfo',
            old_name='details',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='report',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='report',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
        migrations.AddField(
            model_name='criminalinfo',
            name='other_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='location_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='case_status',
            field=models.CharField(choices=[('received', 'تم استلام البلاغ'), ('under_review', 'قيد المراجعة'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تم الحل'), ('closed', 'تم الإغلاق')], default='received', max_length=20),
        ),
    ]
