# Generated by Django 5.2.6 on 2025-09-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_report_location_link_report_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('اعتداء', 'اعتداء'), ('ابتزاز', 'ابتزاز'), ('تحرش', 'تحرش'), ('سرقة', 'سرقة'), ('مشادة', 'مشادة')], default='اعتداء', max_length=20),
        ),
    ]
