# Generated by Django 5.2.6 on 2025-09-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='audio_recording',
            field=models.FileField(blank=True, null=True, upload_to='attachments/audio/'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/files/'),
        ),
    ]
