# Generated by Django 5.2.6 on 2025-09-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_attachment_audio_recording_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
    ]
