# Generated by Django 5.2.6 on 2025-09-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_report_latitude_alter_report_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
    ]
