# Generated by Django 5.2.6 on 2025-09-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_report_latitude_alter_report_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='case_status',
            field=models.CharField(choices=[('received', 'تم استلام البلاغ'), ('under_review', 'قيد المراجعة'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تم الحل'), ('closed', 'تم الإغلاق')], default='resolved', max_length=20),
        ),
    ]
