# Generated by Django 5.2.6 on 2025-09-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_report_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='case_status',
            field=models.CharField(choices=[('تم استلام البلاغ', 'تم استلام البلاغ'), ('قيد المراجعة', 'قيد المراجعة'), ('قيد المعالجة', 'قيد المعالجة'), ('تم الحل', 'تم الحل'), ('تم الإغلاق', 'تم الإغلاق')], default='received', max_length=20),
        ),
    ]
