# Generated by Django 5.2.6 on 2025-09-25 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_alter_report_case_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
    ]
