# Generated by Django 5.2.6 on 2025-09-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_alter_report_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
