# Generated by Django 5.2.6 on 2025-09-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_report_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='location_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
