# Generated by Django 5.2.6 on 2025-09-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_report_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
