# Generated by Django 5.2.6 on 2025-09-26 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_report_is_fake'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='case_status',
            new_name='status',
        ),
    ]
