# Generated by Django 5.2.6 on 2025-09-27 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_rename_case_status_report_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
    ]
