# Generated by Django 5.2.6 on 2025-09-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_alter_report_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='severity',
            field=models.CharField(blank=True, choices=[('حرج', 'حرج'), ('عالية', 'عالية'), ('متوسطة', 'متوسطة'), ('منخفضة', 'منخفضة')], max_length=20, null=True),
        ),
    ]
